version: '3'

services:
  app:
    build:
      context: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 60s entrypoint.sh
    command: node app.js
    tty: true
    networks:
      - application
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - mysql

  nginx:
    image: nginx:1.15.0-alpine
    networks:
      - application
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      - application
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=nodeapp
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  application:
    driver: bridge